<a href="https://colab.research.google.com/github/joaoleal02/Ambev_iHops/blob/master/N-Cluster.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [132]:
import pandas as pd
import datetime
empdata = pd.read_csv(r'tabela_ambev_sql_finale.csv',index_col=False, delimiter=';')
empdata['Doc. Date'] = pd.to_datetime(empdata['Doc. Date'], format='%d/%m/%Y')
dados = empdata.loc[empdata['Postal Code'] == 83630]
#print(dados.head())
teste_tabela = empdata.loc[empdata['Subrand'] == 'BUD']
#teste_tabela =  empdata.loc[empdata['Unidade Container'] != 1]
#teste_tabela = teste_tabela.loc[teste_tabela['Unidade Container'] == 1]
#teste_tabela = teste_tabela.loc[teste_tabela['Subrand'] == 'CORONA EXTRA']
teste_tabela

Doc. Date  Order qty  ...   Preço/L  Container Size 2
10    2021-01-11       70.0  ...  2.629129              6.00
16    2021-01-11       40.0  ...  2.629129              6.00
51    2021-01-12       20.0  ...  2.629129              6.00
55    2021-01-12        1.0  ...  3.092342              7.92
63    2021-01-13      140.0  ...  2.712036              6.00
...          ...        ...  ...       ...               ...
23243 2019-11-22        3.0  ...  2.669880              6.00
23251 2019-11-22        9.0  ...  2.669880              6.00
23259 2019-11-27        1.0  ...  2.768244              6.00
23261 2019-11-27        4.0  ...  2.669880              6.00
23268 2019-11-28        5.0  ...  2.669880              6.00

[1442 rows x 16 columns]

In [133]:

#beer_user = dados.iloc[5]['Subrand']
quantidade_comprada = (dados.iloc[0]['HL delivered'])*100
taxa_recomendacao = 0.1
quantidade_recomendada = quantidade_comprada * taxa_recomendacao 
beer_user = 'LEFFE BLONDE'
# consertar LEFFE RITUEL NA TABELA EMPDATA
print(beer_user)

LEFFE BLONDE


In [134]:
from sklearn.cluster import KMeans
import numpy as np

#importando base de dados
df = pd.read_csv("MLiHops.csv")
df

subrand   ibu  abv (%)  corpo  aroma  tipo  Unnamed: 6
0       BIRRA DEL BORGO  20.0      5.0      1      0    40           0
1                   BUD  10.0      5.0      0      0     2           0
2          CAMDEN HELLS  29.0      4.6      0      0     2           0
3       CAMDEN PALE ALE  39.0      4.0      1      5    40          25
4          CORONA EXTRA  18.0      4.6      0      0     2           0
5       GINETTE BLANCHE  12.0      5.0      0      0    41           0
6        GINETTE BLONDE  29.0      5.0      2      0    40           0
7         GINETTE FRUIT  12.0      4.0      1      5    20          25
8         GINETTE LAGER  25.0      4.5      0      0     2           0
9        GINETTE TRIPLE  15.0      9.0      1     10    44          50
10                GOOSE  55.0      5.9      1      5    45          25
11  HOEGARDEN GRAND CRU  35.0      8.5      1      5    46          25
12       HOEGARDEN ROSE   5.0      3.0      2      5    20          25
13      HOEGARDEN WHITE  15.0      4.9      0      5    41          25
14                 KWAK  16.0      8.4      2      5    46          25
15         LEFFE AMBREE  25.0      6.6      1     15    40          75
16         LEFFE BLONDE  21.5      6.6      0     15    42          75
17     LEFFE BLONDE 0.0  10.0      0.0      0     10    42          50
18          LEFFE BRUNE  20.0      6.5      0     15    43          75
19      LEFFE LA LEGERE  17.0      5.0      0     15     2          75
20       LEFFE RITUEL 9  25.0      9.0      2     15    46          75
21         LEFFE ROYALE  33.0      7.5      1      5    42          25
22           LEFFE RUBY  10.0      5.0      0      5    20          25
23         LEFFE TRIPLE  15.0      8.5      1      5    44          25
24     TRIPLE KARMELIET  31.0      8.4      1     15    44          75

In [135]:
from sklearn.preprocessing import MinMaxScaler

array1 = []

dicRecomendacao = {

  "Harmonizacao": {
  40 : "AMERICAN PALE ALE - Carnes grelhadas e saladas cítricas",
  2: "PALE LAGER - Hamburger, carnes vermelha e petiscos",
  43: "BROWN ALE - Carnes e petiscos",
  41: "WITBIER - Saladas, frutas do mar e comidas leves",
  44: "TRIPEL - Massas e frutos do mar",
  42: "BLONDE - Petiscos e frutos do mar",
  46: "STRONG - Frutos do mar e massas",
  45: "INDIAN PALE ALE - Queijo, carne vermelha, hamburger e petiscos",
  20: "FRUIT BEER - Sobremesa",
  },
  "Temperatura": {
  40: [8, 12],
  2: [0, 4],
  43: [8, 12],
  41: [4, 7],
  44: [4, 7],
  42: [2, 5],
  46: [10, 12],
  45: [8, 12],
  20: [7, 10],
  }
}

for i in range(25):  #itera sobre os valores e adiciona na lista array1

    temp = []
    temp.clear()

    p1 = df.iloc[i]['ibu']
    temp.append(p1)
    p2 = df.iloc[i]['abv (%)']
    temp.append(p2)
    p3 = df.iloc[i]['corpo']
    temp.append(p3)
    p4 = df.iloc[i]['aroma']
    temp.append(p4)
    p5 = df.iloc[i]['tipo']
    temp.append(p5)
    #p6 = dp.iloc[]["preco"]
    #temp.append(p6)

    array1.append(temp)

mms = MinMaxScaler()
X = np.array(array1) #transforma a lista array1 em numpy
mms.fit(X)
data_transformed = mms.transform(X)
print(data_transformed)

print(array1)

[[0.3        0.55555556 0.5        0.         0.86363636]
 [0.1        0.55555556 0.         0.         0.        ]
 [0.48       0.51111111 0.         0.         0.        ]
 [0.68       0.44444444 0.5        0.33333333 0.86363636]
 [0.26       0.51111111 0.         0.         0.        ]
 [0.14       0.55555556 0.         0.         0.88636364]
 [0.48       0.55555556 1.         0.         0.86363636]
 [0.14       0.44444444 0.5        0.33333333 0.40909091]
 [0.4        0.5        0.         0.         0.        ]
 [0.2        1.         0.5        0.66666667 0.95454545]
 [1.         0.65555556 0.5        0.33333333 0.97727273]
 [0.6        0.94444444 0.5        0.33333333 1.        ]
 [0.         0.33333333 1.         0.33333333 0.40909091]
 [0.2        0.54444444 0.         0.33333333 0.88636364]
 [0.22       0.93333333 1.         0.33333333 1.        ]
 [0.4        0.73333333 0.5        1.         0.86363636]
 [0.33       0.73333333 0.         1.         0.90909091]
 [0.1        0

In [136]:
num = 0
num1 = 0
for i in range(2, 15):
  km = KMeans(n_clusters=i, random_state=0)
  km.fit_predict(data_transformed)
  score = silhouette_score(data_transformed, km.labels_, metric='euclidean')
  if score > num:
    num = score
    num1 = i
  else:
    pass
kmeans = KMeans(n_clusters=num1, random_state=0).fit(X)
#pega todas a variaveis e as coloca em 10 grupos (mais parecidas)
tips = kmeans.labels_
print(tips)

[ 2  7  3  0  7  9  2  1  3  9  6  0  1  9  9  4  4  8  4  5 10  0  1  9
 10]


In [137]:
import decimal 

def busca(array,beer):
    for i,el in enumerate(array):
        if el==beer:
            return i
    return None

def arrendondar (x):
    return int(decimal.Decimal(x).quantize(0, decimal.ROUND_HALF_UP))

def sum_array(array):
  if len(array)==0:
    return None
  soma = 0
  for i in array:
    soma += i
  return(soma/len(array))
################################################################################
def DataPreco(data, cerveja,conteiner,filtered_df,contador,quantidade_recomendada):
  mes = data[3:5]
  ano = data[6:]
  dia = data[:2]
  mes_atual = mes
  ano_atual = str(int(ano) - 1)
  dia_atual = dia
  dia30 = [4, 6, 9, 11]
  quantidade_container = 0

  filtered_df = filtered_df.loc[(filtered_df['Doc. Date'] >= f'{dia_atual}/{mes_atual}/{ano_atual}') & (filtered_df['Doc. Date'] < f'{dia_atual}/{mes_atual}/{ano}')]
  filtered_df.sort_values(by=['Doc. Date'], inplace = True, ascending = False)
    
  filtered_df = filtered_df.loc[filtered_df['Unidade Container']==conteiner]

  litros = filtered_df.iloc[0]['Container Size 2']
  #print(conteiner)
  #print(filtered_df.head())
  data_array = filtered_df['Preço/L'].to_numpy()
  media = sum_array(data_array)
  if media != None:
      #print("{1 CAIXA COM %d UNID E %.2f LITROS\npreco medio do L : %.2f"%(conteiner,litros,media))
      #print("1 CAIXA saira por %.2f $ (media * litragem da caixa)\
      #\ncolocar na parte de baixo de uma maneira mais organizada}"%(litros * media))
      if contador == 0:
          print("Recomendamos que voce compre %.2f litros dessa cervaja:"%(quantidade_recomendada))
      
      quantidade_container = arrendondar(quantidade_recomendada/litros)
      print("%d) %d container de %.2f L com %d unidades, com preco media do Litro de %.2f\nDando um total de %.2f $"
            %((contador+1),quantidade_container,litros,conteiner, media, quantidade_container * litros * media))
  return

def funcao(data, cerveja,quantidade_recomendada):
    #fazer lista com os tipos de conteiner da cerveja 
    filtered_df = empdata.loc[empdata["Subrand"] == cerveja]
    #print(filtered_df)
    array_available_conteiners = filtered_df['Unidade Container'].unique()
    
    #print(array_available_conteiners[0])
    num_conteiner = filtered_df['Unidade Container'].nunique()
    c = 0
    conteiner = 0
    while c<num_conteiner:
        DataPreco(data, cerveja,array_available_conteiners[c], filtered_df,c,quantidade_recomendada)
        c+=1
    
    #print("\nRecomendamos que voce compre T litros dessa cervaja:\n1) Y container de X\nDando um total de W $")
    #if True:
     #   print("2) YY container de XX\nDando um total de WW $")
    # preco_medio = 0
    return


In [138]:
beer_array = df['subrand'].to_numpy()
tipo_array = df["tipo"].to_numpy()
Y = busca(beer_array, beer_user)
#print(Y)
qlqr = array1[Y]
a = kmeans.predict([qlqr])
print(a)
var = np.where(tips == a)
#print("\n")
#saida da cerveja
bc = ""
cerveja_escolhida = []
print_out = ""
saida = False
dia_atual = "31/01/2021"
#Ultimo dia da tabela
print(var)
print("------------------------------------------------------------------")
for i in (var):
  for ele in range(len(i)):
    bc = beer_array[i[ele]]
    var_a = i
    var_b = ele
    if bc != beer_user:
      saida = True
      cerveja_escolhida.append(bc)
      ad = i[ele]
      tipo_real = tipo_array[ad]
      #print(tipo_real)
      print("A cerveja recomendada é: ", bc)
      print_out = dicRecomendacao["Harmonizacao"][tipo_real]
      print(print_out)
      print_out = dicRecomendacao["Temperatura"][tipo_real]
      print("A temperatura ideal é entre: %d°C e %d°C\n" %(print_out[0],print_out[1]))
      #print(ad)
      #PRECISA LEVAR EM CONSIDERACAO OS DIFERENTES CONTEINERS -> TEM PRECOS DIFERENTES
      funcao(dia_atual, bc,quantidade_recomendada)
      print("------------------------------------------------------------------")
    

if saida == False:
  print("Nao temos recomendacao")
  print("------------------------------------------------------------------")

[4]
(array([15, 16, 18]),)
------------------------------------------------------------------
A cerveja recomendada é:  LEFFE AMBREE
AMERICAN PALE ALE - Carnes grelhadas e saladas cítricas
A temperatura ideal é entre: 8°C e 12°C

Recomendamos que voce compre 42.00 litros dessa cervaja:
1) 7 container de 6.00 L com 1 unidades, com preco media do Litro de 3.75
Dando um total de 157.56 $
------------------------------------------------------------------
A cerveja recomendada é:  LEFFE BRUNE
BROWN ALE - Carnes e petiscos
A temperatura ideal é entre: 8°C e 12°C

Recomendamos que voce compre 42.00 litros dessa cervaja:
1) 7 container de 6.00 L com 1 unidades, com preco media do Litro de 3.14
Dando um total de 131.89 $
------------------------------------------------------------------


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:31: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:31: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
